language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t skarthik85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skarthik85/docker-react npm run test

