language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t skarthik85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skarthik85/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-781554925155"
  bucket_path: "dockerreact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"